In [3]:
import numpy as np

In [4]:
#cria uma matriz undimensional
mt = np.array ([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [5]:
#criar o array com um tipo específico
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [8]:
#mudar o tipo de array
# podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
#quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [9]:
#criar o array com um tipo especifico
# cria o array como float de 64bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [11]:
#mudar o tipo do array
#podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
#quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [12]:
#podemos fazer o inverso também.
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [13]:
#mais de uma dimensão
#cria uma matriz bidimensional
mt7 = np.array([[7,2,23], [12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [14]:
#criar arrays vazios tipificados
#empty significa que não inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("----")
#com valores igual a um
um = np.ones([5,7])
print(um)
print("--------")
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
----
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
--------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("--------")
#valores aleatórios distr. normal contendo negativas
ale2 = np.random.randn((5))
print(ale2)
print("------")
#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.28225461 0.31260445 0.42241191 0.4006469  0.37971817]
--------
[ 1.36686359  0.76653098  0.82283345 -1.80781532  1.06665191]
------
[[8.04882348 8.68528314 4.32786493 7.29864329]
 [8.25859792 7.50785504 4.64344473 9.51498707]
 [9.39929971 1.6493263  8.74753876 2.69221971]]


In [17]:
#outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [20]:
#funções especificas
#cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
#mostra a matriz k
print(k)
# mostra um elemento especifico da matriz k
print(k[0][1])
# mostra o t amanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [22]:
#Funções Matematicas
# Mostra o maior valor da matriz k
print(k.max())
# MOSTRA  O MENOR VALOR DA MATRIZ K
print(k.min())
# MOSTRA a soma dos valores da matriz k
print((k.sum()))
# Mostra o valor da media dos valores da matriz k
print(k.mean())
# mostra o valor do desviuo padrão (standart deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [24]:
#funções universais, aplicados a todos os elementos 
# mostra o valor da raiz quadrada de todos os elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
# mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [28]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
#mostra o elemento da posição 2
print(m[1])
print("-------")
#mostra o array cirado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
#mostra o array criado a partir do 2a posição
# até todo o restante do array
print(m[1:])
print("------------")
# mostra o array criado a partir da antepenultima
# posição até o final
print(m[-3:])


2
-------
[1 2]
-------
[2 3 4 5 6]
------------
[4 5 6]


In [40]:
#extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("---------")
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("--------")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("---------")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("----------")
#todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)
print("----------")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
---------
[4 5]
--------
[6 1]
---------
[7 4]
----------
[4 6 7]
----------
[5 1 4]


In [43]:
#adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+0
print(res1)
print("-----------")
res2 = n*o
print(res2)
print("----------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[1 2]
 [3 4]]
-----------
[[1 2]
 [3 4]]
----------
[[3 3]
 [5 5]
 [7 7]]


In [45]:
#transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas.
f = np.arange(15).reshape((3,5))
#mostra a matrizes transporta entre linha e coluna
print(f)
print("---------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [47]:
#outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print("---------")
#rearranja um conjunto de 15 elementos
#mostra a matrizes transporta entre linha e coluna
s= r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [48]:
#expressões logicas
#usando where
#criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
#criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
#criando matriz com valores - 1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.0051269   0.34020718  1.97912171 -1.34562572]
 [ 1.49450988 -0.43707678  1.19079401  0.87537311]
 [ 0.15009833  0.48250411  1.28892618  0.48325778]
 [ 0.90026622  0.61087022 -0.66000554  1.28254146]]
[[ True  True  True False]
 [ True False  True  True]
 [ True  True  True  True]
 [ True  True False  True]]
[[ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1  1  1  1]
 [ 1  1 -1  1]]
